// provinces
export const GET_PROVINCES = 'GET_PROVINCES';
export const GET_PROVINCES_PENDING = 'GET_PROVINCES_PENDING';
export const GET_PROVINCES_FULFILLED = 'GET_PROVINCES_FULFILLED';
export const GET_PROVINCES_REJECTED = 'GET_PROVINCES_REJECTED';

// locations
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const GET_LOCATIONS_PENDING = 'GET_LOCATIONS_PENDING';
export const GET_LOCATIONS_FULFILLED = 'GET_LOCATIONS_FULFILLED';
export const GET_LOCATIONS_REJECTED = 'GET_LOCATIONS_REJECTED';

// form
export const POST_FORM = 'POST_FORM';
export const POST_FORM_PENDING = 'POST_FORM_PENDING';
export const POST_FORM_FULFILLED = 'POST_FORM_FULFILLED';
export const POST_FORM_REJECTED = 'POST_FORM_REJECTED';
